name: 'Develop CI workflow'

on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      - '.github/**'

jobs:
  develop-CI:
    runs-on: ubuntu-latest
    steps:
      - name: 'Compilation step'
        run: |
          echo "Compiling..."
          sleep 15s
          echo "Compiled!"
      - name: 'Testing step'
        run: |
          echo "Testing..."
          sleep 15s
          echo "Tested!"
      - name: 'SAST step'
        run: |
          echo "Checking code quality..."
          sleep 15s
          echo "Checked!"
  develop-CD:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: 'Deployment step'
        run: |
          echo "Deploying"..."
          sleep 15s
          echo "Deployed!"