name: 'Develop CD workflow'

on:
  workflow_run:
    workflows: ['Develop CI workflow']
    types: ['completed']

jobs:
  main-CD:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: 'Deployment step'
        run: |
          echo "Deploying"..."
          sleep 15s
          echo "Deployed!"