name: 'Main CD workflow'

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  main-CD:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deployment step'
        run: |
          echo "Deploying"..."
          sleep 15s
          echo "Deployed!"